name: Waka Readme

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M:%S"
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_LOC_CHART: True
          SHOW_LANGUAGE_PER_REPO: True
          DEBUG_LOGGING: True
          SHOW_SHORT_INFO: False
          SYMBOL_VERSION: 3
          COMMIT_BY_ME: True
          COMMIT_MESSAGE: "Update Github Profile by WakaTime"
          COMMIT_USERNAME: ${{ github.repository_owner }}
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          # notify_when: "failure"
          mention_users: "U0160UUNH8S,U0080UUAA9N"
          mention_users_when: "failure,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
