name: Waka Readme

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # meta
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: athul/athul
          # content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          CODE_LANG: last_year 
          TIME_RANGE: true
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          # TARGET_BRANCH: main
          # TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          AUTHOR_NAME: skim
          AUTHOR_EMAIL: ${{ secrets.COMMIT_EMAIL }}
      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          # notify_when: "failure"
          mention_users: "U0160UUNH8S,U0080UUAA9N"
          mention_users_when: "failure,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
